spring:
    application:
        name: bitlab-final-project
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
      hibernate:
          ddl-auto: none
    flyway:
        baselineOnMigrate: true
#flyway:
#    url: jdbc:postgresql://localhost:5432/postgres
#    enabled: true
#    locations:
#        - 'classpath:db/migration'
#    validate-on-migrate: true
api:
    url: "http://localhost:8080/api"
