spring:
    application:
        name: bitlab-final-project
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
    jpa:
      hibernate:
          ddl-auto: none
    flyway:
        baselineOnMigrate: true
        enabled: true
        locations:
            - 'classpath:db/migration'
api:
    url: "http://localhost:8080/api"
