-- insert into users (id, username, uuid, password, first_name, last_name, created_at, updated_at)
-- values ();
--
-- insert into roles (id, name, uuid, created_at, updated_at)
-- values ();
--
-- insert into users_roles (user_id, role_id, created_at, updated_at)
-- values ();
--
-- insert into playing_positions (id, uuid, name, code, created_at, updated_at)
-- values ();
--
-- insert into job_titles (id, name, uuid, created_at, updated_at)
-- values ();
--
-- insert into teams (id, name, uuid, description, user_id, created_at, updated_at)
-- values ();
--
-- insert into staff (id, uuid, first_name, last_name, phone_number, experience, description, job_title_id, team_id,
-- created_at, updated_at)
-- values ();
--
-- insert into players (id, uuid, first_name, last_name, jersey_number, phone_number, birthdate, playing_position_id,
-- team_id, created_at, updated_at)
-- values ();